### ISSUE TITLE
Identity contract: identity creation and modification

### ISSUE THREAD

**Issue by Szegoo** [TheDotflow/dotflow-ink#2]
Brief description of the things we need:
- The Identity contract should have a `Mapping` that maps identities to their own unique `identityNo`
- For each identity, we need to store a list of addresses each of which is associated with a certain blockchain.
- The contract should expose functions that are going to make it possible to create an identity and modify it.

**Comment by cuteolaf** [comment]
- Storage Items
  - **`numberToIdentity`**:  mapping(`IdentityNo` -> `Identity`)
  - **`ownerOf`**: mapping(`identityNo` -> `AccountId`)
  - **`identityOf`**: mapping(`AccountId` -> `IdentityNo`)
  - **`Identity`**: a struct that contains a mapping(`network` -> `address`) and related methods
- Messages(in ink! terms)
  - **`createIdentity`**
      Creates an `Identity` and return the generated `IdentityNo`
  - **`addAddress(network, address)`**
  - **`updateAddress(network, address)`**
  - **`removeAddress(network)`**
  - **`removeIdentity(identityNo)`**

**Comment by Szegoo** [comment]
@cuteolaf Yes, this is what we need. The `ownerOf` mapping will however later change with this PR: https://github.com/TheDotflow/dotflow-ink/issues/5
